### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Parkour#1]
UseNo### Expected behavior

It was reported that addon does not work with the latest BentoBox version.

### Observed/Actual behavior

Addon to work with BentoBox 1.24

### Steps/models to reproduce

Place addon in server and star the server

### BentoBox version

1.24

### Other
https://paste.md-5.net/yowovekuro

**Comment by tastybento** [comment]
Fixed now. It was using a material for the icon in addon.yml that no longer exists. Fix is https://ci.codemc.io/job/BentoBoxWorld/job/Parkour/
